// Docs: https://www.instantdb.com/docs/modeling-data

import { i } from "@instantdb/react-native";

const _schema = i.schema({
  // We inferred 1 attribute!
  // Take a look at this schema, and if everything looks good,
  // run `push schema` again to enforce the types.
  entities: {
    $files: i.entity({
      path: i.string().unique().indexed(),
      url: i.string(),
    }),
    $users: i.entity({
      email: i.string().unique().indexed().optional(),
      imageURL: i.string().optional(),
      type: i.string().optional(),
    }),
    bookings: i.entity({
      bookingnum: i.string(),
      completedat: i.number().optional(),
      confirmedat: i.number().optional(),
      contributorid: i.string(),
      createdat: i.number(),
      date: i.string().indexed(),
      duration: i.number(),
      email: i.string().optional(),
      end: i.string(),
      name: i.string(),
      nodeid: i.string(),
      notes: i.string().optional(),
      paymethod: i.string().optional(),
      paystatus: i.string(),
      phone: i.string(),
      price: i.number(),
      serviceid: i.string(),
      slotid: i.string(),
      start: i.string(),
      status: i.string().indexed(),
    }),
    chat: i.entity({
      contributorid: i.string(),
      conversationid: i.string(),
      createdat: i.number(),
      message: i.string(),
      metadata: i.any().optional(),
      msgtype: i.string(),
      nodeid: i.string().optional(),
    }),
    contributors: i.entity({
      active: i.boolean(),
      address: i.string().optional(),
      avatar: i.string().optional(),
      city: i.string().optional(),
      createdat: i.number(),
      email: i.string().unique(),
      lat: i.number().optional(),
      lng: i.number().optional(),
      name: i.string(),
      phone: i.string().optional(),
      role: i.string(),
      updatedat: i.number(),
    }),
    conversations: i.entity({
      context: i.any().optional(),
      contributorid: i.string(),
      createdat: i.number(),
      lastactivity: i.number(),
      title: i.string().optional(),
      updatedat: i.number(),
    }),
    instances: i.entity({
      active: i.boolean(),
      attrs: i.json().optional(),
      available: i.number(),
      createdat: i.number(),
      instancetype: i.string(),
      name: i.string(),
      nodeid: i.string(),
      priceadd: i.number(),
      productid: i.string(),
      qty: i.number(),
      reserved: i.number(),
      serial: i.string().optional(),
      sku: i.string().optional(),
      status: i.string(),
      updatedat: i.number(),
    }),
    lineitems: i.entity({
      createdat: i.number(),
      instanceid: i.string().optional(),
      instancename: i.string().optional(),
      name: i.string(),
      notes: i.string().optional(),
      orderid: i.string(),
      productid: i.string(),
      qty: i.number(),
      total: i.number(),
      unitprice: i.number(),
    }),
    memories: i.entity({
      content: i.string(),
      contributorid: i.string(),
      conversationid: i.string(),
      createdat: i.number(),
      metadata: i.any().optional(),
      role: i.string(),
    }),
    nodes: i.entity({
      address: i.string(),
      avatar: i.string().optional(),
      bio: i.string().optional(),
      city: i.string(),
      close: i.string(),
      commission: i.number(),
      cover: i.string().optional(),
      createdat: i.number(),
      days: i.string(),
      email: i.string().optional(),
      isopen: i.boolean(),
      lat: i.number(),
      lng: i.number(),
      name: i.string().indexed(),
      open: i.string(),
      phone: i.string(),
      rating: i.number(),
      type: i.string(),
      updatedat: i.number(),
      verified: i.boolean(),
    }),
    orders: i.entity({
      address: i.string().optional(),
      confirmedat: i.number().optional(),
      contributorid: i.string(),
      createdat: i.number(),
      currency: i.string(),
      deliveredat: i.number().optional(),
      deliveryfee: i.number(),
      discount: i.number(),
      driverid: i.string().optional(),
      estimateddelivery: i.number().optional(),
      lat: i.number().optional(),
      lng: i.number().optional(),
      nodeid: i.string(),
      ordernum: i.string(),
      ordertype: i.string(),
      paymethod: i.string().optional(),
      paystatus: i.string(),
      phone: i.string().optional(),
      status: i.string().indexed(),
      subtotal: i.number(),
      tax: i.number(),
      total: i.number(),
    }),
    products: i.entity({
      active: i.boolean(),
      category: i.string(),
      createdat: i.number(),
      currency: i.string(),
      desc: i.string().optional(),
      featured: i.boolean(),
      image: i.string().optional(),
      images: i.any().optional(),
      instock: i.boolean(),
      name: i.string().indexed(),
      nodeid: i.string(),
      oldprice: i.number().optional(),
      price: i.number(),
      stock: i.number(),
      updatedat: i.number(),
    }),
    reviews: i.entity({
      comment: i.string().optional(),
      contributorid: i.string(),
      createdat: i.number(),
      images: i.any().optional(),
      rating: i.number(),
      targetid: i.string(),
      targettype: i.string(),
      verified: i.boolean(),
    }),
    services: i.entity({
      active: i.boolean(),
      category: i.string(),
      createdat: i.number(),
      currency: i.string(),
      desc: i.string().optional(),
      duration: i.number(),
      image: i.string().optional(),
      maxperslot: i.number(),
      name: i.string().indexed(),
      needapproval: i.boolean(),
      nodeid: i.string(),
      price: i.number(),
      pricetype: i.string(),
      updatedat: i.number(),
    }),
    slots: i.entity({
      booked: i.number(),
      capacity: i.number(),
      createdat: i.number(),
      date: i.string().indexed(),
      end: i.string(),
      nodeid: i.string(),
      serviceid: i.string(),
      start: i.string(),
      status: i.string().indexed(),
    }),
    tasks: i.entity({
      assignedat: i.number().optional(),
      assignedto: i.string().optional(),
      completedat: i.number().optional(),
      createdat: i.number(),
      dependson: i.string().optional(),
      dueat: i.number().optional(),
      lastloc: i.number().optional(),
      lat: i.number().optional(),
      lng: i.number().optional(),
      needotp: i.boolean(),
      nodeid: i.string(),
      notes: i.string().optional(),
      otp: i.string().optional(),
      relid: i.string(),
      reltype: i.string(),
      seq: i.number(),
      startedat: i.number().optional(),
      status: i.string().indexed(),
      tasktype: i.string(),
      title: i.string(),
      trackloc: i.boolean(),
      updatedat: i.number(),
      verifiedat: i.number().optional(),
    }),
    transactions: i.entity({
      amount: i.number(),
      bookingid: i.string().unique().optional(),
      contributorid: i.string(),
      createdat: i.number(),
      currency: i.string(),
      nodefee: i.number(),
      nodeid: i.string(),
      orderid: i.string().unique().optional(),
      paymethod: i.string(),
      payref: i.string().optional(),
      platformfee: i.number(),
      refundamount: i.number().optional(),
      refundedat: i.number().optional(),
      status: i.string(),
    }),
  },
  links: {
    $usersLinkedPrimaryUser: {
      forward: {
        on: "$users",
        has: "one",
        label: "linkedPrimaryUser",
        onDelete: "cascade",
      },
      reverse: {
        on: "$users",
        has: "many",
        label: "linkedGuestUsers",
      },
    },
    bookingsContributor: {
      forward: {
        on: "bookings",
        has: "one",
        label: "contributor",
      },
      reverse: {
        on: "contributors",
        has: "many",
        label: "bookings",
      },
    },
    bookingsService: {
      forward: {
        on: "bookings",
        has: "one",
        label: "service",
      },
      reverse: {
        on: "services",
        has: "many",
        label: "bookings",
      },
    },
    bookingsSlot: {
      forward: {
        on: "bookings",
        has: "one",
        label: "slot",
      },
      reverse: {
        on: "slots",
        has: "one",
        label: "booking",
      },
    },
    chatContributor: {
      forward: {
        on: "chat",
        has: "one",
        label: "contributor",
      },
      reverse: {
        on: "contributors",
        has: "many",
        label: "chat",
      },
    },
    chatConversation: {
      forward: {
        on: "chat",
        has: "one",
        label: "conversation",
      },
      reverse: {
        on: "conversations",
        has: "many",
        label: "chat",
      },
    },
    chatNode: {
      forward: {
        on: "chat",
        has: "one",
        label: "node",
      },
      reverse: {
        on: "nodes",
        has: "many",
        label: "chat",
      },
    },
    conversationsContributor: {
      forward: {
        on: "conversations",
        has: "one",
        label: "contributor",
      },
      reverse: {
        on: "contributors",
        has: "many",
        label: "conversations",
      },
    },
    instancesNode: {
      forward: {
        on: "instances",
        has: "one",
        label: "node",
      },
      reverse: {
        on: "nodes",
        has: "many",
        label: "instances",
      },
    },
    instancesProduct: {
      forward: {
        on: "instances",
        has: "one",
        label: "product",
      },
      reverse: {
        on: "products",
        has: "many",
        label: "instances",
      },
    },
    lineitemsOrder: {
      forward: {
        on: "lineitems",
        has: "one",
        label: "order",
      },
      reverse: {
        on: "orders",
        has: "many",
        label: "lineitems",
      },
    },
    memoriesConversation: {
      forward: {
        on: "memories",
        has: "one",
        label: "conversation",
      },
      reverse: {
        on: "conversations",
        has: "many",
        label: "memories",
      },
    },
    ordersContributor: {
      forward: {
        on: "orders",
        has: "one",
        label: "contributor",
      },
      reverse: {
        on: "contributors",
        has: "many",
        label: "orders",
      },
    },
    ordersNode: {
      forward: {
        on: "orders",
        has: "one",
        label: "node",
      },
      reverse: {
        on: "nodes",
        has: "many",
        label: "orders",
      },
    },
    productsNode: {
      forward: {
        on: "products",
        has: "one",
        label: "node",
      },
      reverse: {
        on: "nodes",
        has: "many",
        label: "products",
      },
    },
    reviewsContributor: {
      forward: {
        on: "reviews",
        has: "one",
        label: "contributor",
      },
      reverse: {
        on: "contributors",
        has: "many",
        label: "reviews",
      },
    },
    servicesNode: {
      forward: {
        on: "services",
        has: "one",
        label: "node",
      },
      reverse: {
        on: "nodes",
        has: "many",
        label: "services",
      },
    },
    slotsService: {
      forward: {
        on: "slots",
        has: "one",
        label: "service",
      },
      reverse: {
        on: "services",
        has: "many",
        label: "slots",
      },
    },
    tasksAssignedcontributor: {
      forward: {
        on: "tasks",
        has: "one",
        label: "assignedcontributor",
      },
      reverse: {
        on: "contributors",
        has: "many",
        label: "assignedtasks",
      },
    },
    tasksBooking: {
      forward: {
        on: "tasks",
        has: "one",
        label: "booking",
      },
      reverse: {
        on: "bookings",
        has: "many",
        label: "tasks",
      },
    },
    tasksDependstask: {
      forward: {
        on: "tasks",
        has: "one",
        label: "dependstask",
      },
      reverse: {
        on: "tasks",
        has: "many",
        label: "blockedtasks",
      },
    },
    tasksNode: {
      forward: {
        on: "tasks",
        has: "one",
        label: "node",
      },
      reverse: {
        on: "nodes",
        has: "many",
        label: "tasks",
      },
    },
    tasksOrder: {
      forward: {
        on: "tasks",
        has: "one",
        label: "order",
      },
      reverse: {
        on: "orders",
        has: "many",
        label: "tasks",
      },
    },
    transactionsBooking: {
      forward: {
        on: "transactions",
        has: "one",
        label: "booking",
      },
      reverse: {
        on: "bookings",
        has: "one",
        label: "transaction",
      },
    },
    transactionsContributor: {
      forward: {
        on: "transactions",
        has: "one",
        label: "contributor",
      },
      reverse: {
        on: "contributors",
        has: "many",
        label: "transactions",
      },
    },
    transactionsNode: {
      forward: {
        on: "transactions",
        has: "one",
        label: "node",
      },
      reverse: {
        on: "nodes",
        has: "many",
        label: "transactions",
      },
    },
    transactionsOrder: {
      forward: {
        on: "transactions",
        has: "one",
        label: "order",
      },
      reverse: {
        on: "orders",
        has: "one",
        label: "transaction",
      },
    },
  },
  rooms: {},
});

// This helps Typescript display nicer intellisense
type _AppSchema = typeof _schema;
interface AppSchema extends _AppSchema {}
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
